# 零Bug测试体系 - Pre-commit Hooks
# 确保所有代码在提交前都经过严格的质量检查

repos:
  # 基础代码格式和质量检查
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --extend-ignore=E203,W503
          - --select=B,C,E,F,W,T4,B9
          - --max-complexity=10
          - --max-args=7
        additional_dependencies:
          - flake8-docstrings
          - flake8-import-order
          - flake8-bugbear
          - pep8-naming

  # 代码格式化
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile black
          - --line-length=88
          - --known-first-party=src

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        line_length: 88

  # 类型检查
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-all
          - types-requests
          - types-setuptools
        args:
          - --strict
          - --warn-return-any
          - --warn-unused-ignores
          - --warn-redundant-casts
          - --no-implicit-optional
          - --disallow-untyped-defs
          - --disallow-incomplete-defs
          - --check-untyped-defs

  # 安全检查
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args:
          -r
          -c
          --severity-level=medium
        exclude: ^tests/.*$

  # 文本检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: name-tests-test

  # 依赖安全检查
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
          - --convention=google
        exclude: tests/.*

  # 导入检查
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.4
    hooks:
      - id: pylint
        args:
          - --rcfile=.pylintrc
          - --max-line-length=88
          - --disable=R0801,C0114,C0115,C0116
        additional_dependencies:
          - pylint-django
          - pylint-flask
          - pylint-pytest
        exclude: tests/.*