#!/bin/bash
# 服务器端SSH问题排查命令

echo "=================================="
echo "🔧 服务器端SSH问题排查命令"
echo "=================================="

echo ""
echo "1. 检查SSH服务状态："
echo "   systemctl status sshd"
echo "   # 如果没有运行，启动它："
echo "   systemctl start sshd"
echo "   systemctl enable sshd"
echo ""

echo "2. 检查SSH配置："
echo "   cat /etc/ssh/sshd_config | grep -E '(PermitRootLogin|PasswordAuthentication|PubkeyAuthentication)'"
echo "   # 确保配置正确："
echo "   PermitRootLogin yes"
echo "   PasswordAuthentication yes"
echo "   PubkeyAuthentication yes"
echo ""

echo "3. 重启SSH服务："
echo "   systemctl restart sshd"
echo ""

echo "4. 检查SSH日志："
echo "   tail -f /var/log/auth.log"
echo "   # 或者："
echo "   journalctl -u sshd -f"
echo ""

echo "5. 检查防火墙状态："
echo "   ufw status"
echo "   # 如果SSH端口被阻止："
echo "   ufw allow 22/tcp"
echo ""

echo "6. 检查fail2ban状态："
echo "   fail2ban-client status"
echo "   fail2ban-client status sshd"
echo "   # 如果IP被阻止，解封："
echo "   fail2ban-client set sshd unbanip YOUR_IP_ADDRESS"
echo ""

echo "7. 检查系统资源："
echo "   free -h"
echo "   df -h"
echo "   top"
echo ""

echo "8. 检查网络连接："
echo "   netstat -tlnp | grep :22"
echo "   ss -tlnp | grep :22"
echo ""

echo "9. 测试SSH连接（在服务器上）："
echo "   ssh localhost"
echo "   ssh root@localhost"
echo ""

echo "10. 重新生成SSH主机密钥（如果需要）："
echo "    rm /etc/ssh/ssh_host_*"
echo "    ssh-keygen -A"
echo "    systemctl restart sshd"
echo ""

echo "=================================="
echo "💡 常见解决步骤："
echo "1. 先检查SSH服务状态和日志"
echo "2. 查看是否有IP被fail2ban阻止"
echo "3. 重启SSH服务"
echo "4. 检查防火墙设置"
echo "=================================="